# Generated by Django 5.1.5 on 2025-01-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='setor',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('financeiro', 'Financeiro'), ('vendas', 'Vendas'), ('estoque', 'Estoque')], default='administrativo', max_length=20),
        ),
    ]
