# Generated by Django 5.1.5 on 2025-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instancia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instância'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='setor',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('financeiro', 'Financeiro'), ('vendas', 'Vendas'), ('estoque', 'Estoque')], default='administrativo', max_length=20, verbose_name='Setor'),
        ),
    ]
